### ISSUE TITLE
Allow multiple companion apps

### ISSUE THREAD

**Issue by BLACK4585** [ASchoe311/RiotGamesLibrary#1]
I think it would be nice to support multiple companion apps, so multiple input fields would be nice.
I personally use Overwolf with Valo Tracker and Blitz in Valo and am currently using the script feature in PN to start and end the applications around the game automatically.

**Comment by ASchoe311** [comment]
This is a great idea, will put this in the next update. Also I released a fix already for overwolf-based companion apps that hasn't been propagated to the playnite addon database yet due to an installer manifest issue. You can install that here https://github.com/ASchoe311/RiotGamesLibrary/releases/tag/v2.0

**Comment by ASchoe311** [comment]
Multiple companion app support is finished, but I'm gonna make a few more bug fixes and improvements before officially releasing it. If you want to use it in the meantime you can install it here https://github.com/ASchoe311/RiotGamesLibrary/blob/MultipleCompanions/Packed/RiotGamesLibrary_91d13c6f-63d3-42ed-a100-6f811a8387ea_2_1_0.pext

**Comment by BLACK4585** [comment]
Nice thank you very much!

**Comment by ASchoe311** [comment]
Would love some feedback on it if there is any after you've gotten the chance to use it
